---
- name: Configure base image
  hosts: all
  gather_facts: true
  vars:
    # These should be a bare-minimum set of packages needed for:
    #  - booting
    #  - networking
    #  - filesystem
    #  - initial provisioning upon boot
    #  - troubleshooting of actions within the above stages of lifecycle
    system_packages:
      baseline:
      - apt-transport-https
      - bsdextrautils
      - btrfs-progs
      - ca-certificates
      - curl
      - dnsutils
      - dosfstools
      - e2fsprogs
      - fdisk
      - gnupg
      - jq
      - less
      - lsb-release
      - lsof
      - lz4
      - netcat-openbsd
      - net-tools
      - nfs-common
      - openssl
      - open-iscsi
      - parted
      - pv
      - vim
      - wget
      - wireguard
      - zstd
      by_release:
        jammy:
          raspi:
          - linux-modules-extra-raspi
          any:
          - efibootmgr
          - grub2-common
          - grub-efi-amd64
        noble:
          raspi: []
          any:
          - efibootmgr
          - grub2-common
          - grub-efi-amd64
    # yamllint disable rule:line-length
    required_packages: "{{ system_packages.baseline + system_packages.by_release[ansible_distribution_release][device_type] }}"

  tasks:
  - name: "Setup Ubuntu OS"
    ansible.builtin.include_role:
      name: homelab_ops.os.ubuntu
    vars:
      ubuntu:
        initrd:
          iscsi_root_fs_enabled: true
        kernel:
          modules:
          - br_netfilter
          - overlay
          - iscsi_tcp
          parameters:
            net.ipv4.ip_forward: 1
            net.ipv6.conf.all.forwarding: 1
            fs.inotify.max_user_watches: 1048576
            fs.inotify.max_user_instances: 1048576
          upgrade: true
        packages:
          install: "{{ required_packages }}"
          remove:
          - name: modemmanager
            systemd_services: [ModemManager]
          - name: snapd
            systemd_services: [snapd]
            directories:
            - /snap
            - /var/snap
            - /var/lib/snapd
            - /var/cache/snapd
            - /usr/lib/snapd
            - /root/snap
            reinstall: prevent
          - name: squashfs-tools
          - name: telnet
          - name: ufw
          - name: unattended-upgrades
            systemd_services: [unattended-upgrades]
            reinstall: prevent
          - name: wpasupplicant
            systemd_services: [wpa_supplicant]
          - name: xauth
        services:
          mask:
          - apt-daily-upgrade.service
          - apt-daily.service
          disable:
          - apt-daily-upgrade.timer
          - apt-daily.timer
