---
- name: Configure base image
  hosts: all
  gather_facts: true
  tasks:
  - name: "Setup Ubuntu OS"
    ansible.builtin.include_role:
      name: homelab_ops.os.ubuntu
    vars:
      ubuntu:
        kernel:
          modules:
          - br_netfilter
          - overlay
          - iscsi_tcp
          parameters:
            net.ipv4.ip_forward: 1
            net.ipv6.conf.all.forwarding: 1
            fs.inotify.max_user_watches: 1048576
            fs.inotify.max_user_instances: 1048576
          upgrade: true
        packages:
          install:
          # These should be a bare-minimum set of packages needed for:
          #  - booting
          #  - networking
          #  - filesystem
          #  - initial provisioning upon boot
          #  - troubleshooting of actions within the above stages of lifecycle
          - btrfs-progs
          - dnsutils
          - fdisk
          - gnupg
          - jq
          - less
          - lsb-release
          - lsof
          - lz4
          - netcat-openbsd
          - net-tools
          - nfs-common
          - open-iscsi
          - parted
          - pv
          - vim
          - wireguard
          - zstd
          remove:
          - name: modemmanager
            systemd_services: [ModemManager]
          - name: snapd
            systemd_services: [snapd]
            directories:
            - /snap
            - /var/snap
            - /var/lib/snapd
            - /var/cache/snapd
            - /usr/lib/snapd
            - /root/snap
            reinstall: prevent
          - name: squashfs-tools
          - name: telnet
          - name: ufw
          - name: unattended-upgrades
            systemd_services: [unattended-upgrades]
            reinstall: prevent
          - name: wpasupplicant
            systemd_services: [wpa_supplicant]
          - name: xauth
        services:
          mask:
          - apt-daily-upgrade.service
          - apt-daily.service
          disable:
          - apt-daily-upgrade.timer
          - apt-daily.timer
